### ISSUE TITLE
pyntc error when running file_copy module

### ISSUE THREAD

**Issue by AnasTarsha** [networktocode/ntc-ansible#146] opened 2016-12-19 06:11 UTC
I'm getting a "pyntc Python library not found." error when I try to run the ntc_copy_file module (or any module that depends on pyntc). I already have pyntc installed and cannot figure out why I keep getting this error. Any insight would be great.

  - hosts: all
    connection: local
    gather_facts: False

  tasks:
  - ntc_file_copy:
     platform: cisco_ios_ssh
     local_file: file.bin
     host: "{{ inventory_hostname }}"
     username: cisco
     password: cisco

Thanks,
Anas

**Comment by GGabriele** [comment] 2016-12-19 08:11
Hi @anastarsha ,
are you running this on your main environment or on a virtual one?

Can you confirm this works for you?:

```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyntc
>>> 
```

**Comment by anastarsha** [comment] 2016-12-19 09:04
Running it on the main environment. I'm getting the following error when I try to import pyntc, I followed the provided instructions to install pyntc on Ubuntu. 

>>> import pyntc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/__init__.py", line 6, in <module>
    from .devices import supported_devices, DEVICE_CLASS_KEY
  File "/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/__init__.py", line 6, in <module>
    from .nxos_device import NXOSDevice, NXOS_API_DEVICE_TYPE
  File "/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/nxos_device.py", line 10, in <module>
    from pynxos.device import Device as NXOSNative
  File "build/bdist.linux-x86_64/egg/pynxos/device.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/pynxos/lib/rpc_client.py", line 5, in <module>
ImportError: No module named builtins

**Comment by GGabriele** [comment] 2016-12-19 12:46
It seems there's a missing library. 

`sudo pip install future` should solve this.

**Comment by anastarsha** [comment] 2016-12-20 22:36
Thanks much @GGabriele, that fixed the issue. Just curious, why is the future library needed here? I don't see this library being mentioned in the installation instructions so it might be helpful to list it as prerequisite in case others run into the same problem.

**Comment by GGabriele** [comment] 2016-12-21 07:23
Great.
`future` is installed as requirement for `pyntc` but probably something went wrong when you installed it. Do you remember if you did it via `pip` or source code?

**Comment by anastarsha** [comment] 2016-12-22 19:07
pip never worked for me so i used the source  code. I need to go back and check but apparently that either didn't include the future library or that library install failed. Tried that twice.

**Comment by anastarsha** [comment] 2017-01-03 03:48
Hi @GGabriele, 

The ntc_file_copy module always fails with the following error when I try to copy a file larger than 150M. Am I missing something? It works ok with smaller files. Thanks.

fatal: [csr3]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ntc_file_copy"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_en0R76/ansible_module_ntc_file_copy.py\", line 274, in <module>\n    main()\n  File \"/tmp/ansible_en0R76/ansible_module_ntc_file_copy.py\", line 243, in main\n    remote_exists = device.file_copy_remote_exists(local_file, remote_file)\n  File \"/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py\", line 138, in file_copy_remote_exists\n    fc = self._file_copy_instance(src, dest, file_system=file_system)\n  File \"/usr/local/lib/python2.7/dist-packages/pyntc-0.0.5-py2.7.egg/pyntc/devices/ios_device.py\", line 134, in _file_copy_instance\n    fc = FileTransfer(self.native, src, dest, file_system=file_system)\n  File \"/usr/local/lib/python2.7/dist-packages/netmiko-1.1.0-py2.7.egg/netmiko/scp_handler.py\", line 76, in __init__\n  File \"/usr/local/lib/python2.7/dist-packages/netmiko-1.1.0-py2.7.egg/netmiko/scp_handler.py\", line 169, in file_md5\nMemoryError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"

**Comment by GGabriele** [comment] 2017-01-03 12:44
I read `MemoryError` there...can you confirm your device has enough free space?

**Comment by anastarsha** [comment] 2017-01-03 18:15
The router bootflash has over 6G of free space and I'm able to copy the same file to the router using SCP from the same host Ansible is running on.

**Comment by itdependsnetworks** [comment] 2017-07-10 03:57
This may be related: https://github.com/ktbyers/netmiko/issues/491

That being said, does this work in netmiko?

**Comment by itdependsnetworks** [comment] 2018-01-22 05:00
Should be able to close this, I think the issue is either resolved or better suited to be addressed in netmiko.

**Closed by itdependsnetworks** 2018-01-22 05:00 UTC
